=== Trisqui36/lenguajes-de-marcas/unidad-03/xml-dtd/tareas /carta.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="carta">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="informacion">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="ubicacion" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="seccion" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string"/>
                            <xs:element name="plato" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="descripcion" type="xs:string" minOccurs="0"/>
                                        <xs:element name="precio">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:decimal">
                                                        <xs:attribute name="moneda" type="xs:string" fixed="EUR"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="recomendacion" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:attribute name="plato" type="xs:IDREF" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:ID" use="required"/>
                                    <xs:attribute name="alergenos" type="xs:string"/>
                                    <xs:attribute name="vegano" type="xs:boolean" use="optional" default="false"/>
                                    <xs:attribute name='frio' type='xs:boolean' default='false'/>
                                    <xs:attribute name="recomendado" type="xs:boolean" default="false"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="tipo" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="entrante"/>
                                    <xs:enumeration value="principales"/>
                                    <xs:enumeration value="postres"/>
                                    <xs:enumeration value="bebidas"/>
                                </xs:restriction> 
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name='reservas'>
                    <xs:complexType>
                        <xs:sequence>
                              <xs:element name="reserva" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="client" type="xs:string"/>
                            <xs:element name="fecha" type="xs:date"/>
                            <xs:element name="personas">
                                <xs:simpleType>
                                    <xs:restriction base="xs:positiveInteger">
                                        <xs:maxInclusive value="20"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID" use="required"/>
                        <xs:attribute name="plato" type="xs:IDREF" use="optional"/>
                        <xs:attribute name="estado" default="pendiente">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="confirmado"/>
                                    <xs:enumeration value="cancelada"/>
                                    <xs:enumeration value="pendiente"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                        </xs:sequence> 
                    </xs:complexType>   
                </xs:element> 
            </xs:sequence>
            <xs:attribute name="nombre" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Trisqui36/lenguajes-de-marcas/unidad-03/xml-dtd/tareas /carta-xsd.xml
<?xml version="1.0" encoding="UTF-8"?>


<carta xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
xsi:noNamespaceSchemaLocation='carta.xsd'
nombre='El platano canario'>
    <informacion> 
        <nombre> El Platano canario </nombre>
        <ubicacion>Icod de los Vinos, Tenerife</ubicacion>
    </informacion>
    <seccion tipo='entrante'>
        <titulo>Para compartir</titulo>
        <plato id='P01' alergenos='gluten' vegano='false'>
            <nombre>Queso asado</nombre>
            <descripcion>Queso canario con mojo rojo y verde</descripcion>
            <precio moneda='EUR'>8.00</precio>
            <recomendacion plato='P01' />
        </plato>
        <plato id='P02' alergenos='gluten' vegano='true'>
            <nombre>Papas arrugadas</nombre>
            <descripcion>Papas con mojo</descripcion>
            <precio moneda='EUR'>4.00</precio>
        </plato>
    </seccion>
    <!--Postres de la carta-->
    <seccion tipo='postres'>
        <titulo>Para disfrutar</titulo>
        <plato id='P03' frio='true' recomendado='true'>
            <nombre>Brownie</nombre>
            <descripcion>Brownie de chocolate con nueces</descripcion>
            <precio moneda='EUR'>2.00</precio>
        </plato>
        <plato id='P04' frio='false'>
            <nombre>Helado de vainilla</nombre>
            <descripcion>Bola de helado de vainilla con sirope a elegir entre chocolate, caramelo o fresa</descripcion>
            <precio moneda='EUR'>8.00</precio>
        </plato>
    </seccion>
    <reservas> 
        <reserva id='R1' estado="pendiente">
            <client> Maria </client>
            <fecha>2026-10-25 </fecha>
            <personas> 2 </personas>
        </reserva>   
        <reserva id='R2' estado="confirmado" plato="P01">
            <client> Gerald </client>
            <fecha>2007-06-04</fecha>
            <personas> 2 </personas>
        </reserva>   
    </reservas>


</carta>
