=== Trisqui36/lenguajes-de-marcas/unidad-03/xml-dtd/carta.dtd
<!ELEMENT carta (informacion, seccion+,reservas*)> <!-- Signo +: aparece una o mas veces -->
<!ELEMENT recomendacion EMPTY>

<!ELEMENT informacion (nombre, ubicacion)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT ubicacion (#PCDATA)>

<!ELEMENT seccion (titulo, plato+)>
<!ELEMENT titulo (#PCDATA)>

<!ELEMENT plato (nombre, descripcion, precio, recomendacion*)>
<!-- No ponemos la linea de nombre pq coge la de arriba -->
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT precio (#PCDATA)>

<!ELEMENT reservas (reserva*)>
<!ELEMENT reserva  (client, fecha, personas)>

<!ELEMENT client (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT personas (#PCDATA)>


<!ENTITY nombreLocal 'El platano canario'>

<!-- CARDINALIDADES -->
<!-- Sin simbolo: aparece exactamente una vez -->
<!-- ?: aparece cero o una vez -->
<!--: aparece cero o mas veces -->
<!-- +: aparece una o mas veces -->

<!ATTLIST carta 
    nombre CDATA #REQUIRED>

<!ATTLIST seccion
    tipo (entrantes | principales | bebidas | postres ) #REQUIRED>

<!ATTLIST plato
    id ID #REQUIRED
    alergenos CDATA #IMPLIED 
    vegano (TRUE | FALSE) 'FALSE'
    recomendado (TRUE | FALSE) 'FALSE'
    frio (TRUE | FALSE) 'FALSE'>

<!ATTLIST precio
    moneda (EUR | PLZ | GBP) #FIXED 'EUR'> <!-- EUR: euro; PLZ: moneda de polonia; GBP: libra -->

<!-- EXPLICACIONES -->
<!-- PCDATA: define que es texto -->
<!-- IMPLIED: el atributo es opcional -->
<!-- FIXED: unicamente sirve ese valor (en el ejemplo no tiene sentido poner mas opciones cuando solo sirve una) -->

<!ATTLIST recomendacion
    plato IDREF #REQUIRED>
<!ATTLIST reserva
    id ID #REQUIRED
    plato IDREF #IMPLIED
    estado (pendeinte| confirmado| cancelado) 'pendiente'>

    <!--xsd tiene xs:string, xs:date, y xs:decimal-->
    <!--minoccurs y maxoccurs-->
    <!--enumaraciones,minimos,maximos,patrones.-->
    <!--muchos tipos para elementos y atributos -->

=== Trisqui36/lenguajes-de-marcas/unidad-03/xml-dtd/carta.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE carta SYSTEM "carta.dtd">

<carta nombre='El platano canario'>
    <informacion> 
        <nombre>&nombreLocal;</nombre>
        <ubicacion>Icod de los Vinos, Tenerife</ubicacion>
    </informacion>
    <seccion tipo='entrantes'>
        <titulo>Para compartir</titulo>
        <plato id='P01' alergenos='gluten' vegano='FALSE'>
            <nombre>Queso asado</nombre>
            <descripcion>Queso canario con mojo rojo y verde</descripcion>
            <precio moneda='EUR'>8.00</precio>
            <recomendacion plato='P01' />
        </plato>
        <plato id='P02' alergenos='gluten' vegano='TRUE'>
            <nombre>Papas arrugadas</nombre>
            <descripcion>Papas con mojo</descripcion>
            <precio moneda='EUR'>4.00</precio>
        </plato>
    </seccion>
    <!--Postres de la carta-->
    <seccion tipo='postres'>
        <titulo>Para disfrutar</titulo>
        <plato id='P03' frio='TRUE' recomendado='TRUE'>
            <nombre>Brownie</nombre>
            <descripcion>Brownie de chocolate con nueces</descripcion>
            <precio moneda='EUR'>2.00</precio>
        </plato>
        <plato id='P04' frio='FALSE'>
            <nombre>Helado de vainilla</nombre>
            <descripcion>Bola de helado de vainilla con sirope a elegir entre chocolate, caramelo o fresa</descripcion>
            <precio moneda='EUR'>8.00</precio>
        </plato>
    </seccion>
    <reservas> 
        <reserva id='R1' estado="pendeinte">
            <client> Maria </client>
            <fecha> 25/10/2026 </fecha>
            <personas> 2 </personas>
        </reserva>   
        <reserva id='R2' estado="confirmado" plato="P01">
            <client> Gerald </client>
            <fecha> 04/06/2007 </fecha>
            <personas> 2 </personas>
        </reserva>   
    </reservas>


</carta>
